#!/bin/bash
DIR=../tests/correctness/resources/miniboxing/tests/compile/

if [ $# -lt 1 -o ! -f "$1" ]
then
  echo "$0 <test file>"
  exit 1
fi

FILE=$1
shift

FILE_NAME=$FILE
FILE_NAME=${FILE_NAME%\.scala}
FILE_NAME=${FILE_NAME%\.repl}

# file
cp $FILE $DIR

# command-line args
if [ $# -eq 0 ]
then
  $EDITOR $DIR/"$FILE_NAME".flags
else
  echo $@ > $DIR/"$FILE_NAME".flags
fi

# checked output
$EDITOR $DIR/"$FILE_NAME".check
sed -i "s/$FILE/newSource1.scala/" $DIR/"$FILE_NAME".check

# launch configuration
$EDITOR $DIR/"$FILE_NAME".launch
ls $DIR/"$FILE_NAME"*
