#!/bin/bash

if [ "$MINIBOXING_PATH" == "" -o "$SCALA_PATH" == "" -o ! -f $SCALA_PATH/scalac -o ! -d $MINIBOXING_PATH/components ]
then
  echo To use this script please set the MINIBOXING_PATH and SCALA_PATH environment variables such that:
  echo " -" '$SCALA_PATH/scalac' "(currently $SCALA_PATH/scalac)"
  echo " -" '$MINIBOXING_PATH/components' "(currently $MINIBOXING_PATH/components)"
  echo are accessible
  exit 1
fi

SCALA_VERSION=2.10
MINIBOXING_VERSION=0.1
PLUGIN_JAR=$MINIBOXING_PATH/components/plugin/target/scala-$SCALA_VERSION/miniboxing-plugin_$SCALA_VERSION-$MINIBOXING_VERSION-SNAPSHOT.jar
RUNTIME_JAR=$MINIBOXING_PATH/components/runtime/target/scala-$SCALA_VERSION/miniboxing-runtime_$SCALA_VERSION-$MINIBOXING_VERSION-SNAPSHOT.jar

$SCALA_PATH/scalac -cp $RUNTIME_JAR:$PLUGIN_JAR -Xplugin:$PLUGIN_JAR $@
