#!/bin/bash

if [ "$MINIBOXING_PATH" == "" -o "$SCALA_PATH" == "" -o ! -f $SCALA_PATH/scalac -o ! -d $MINIBOXING_PATH/components ]
then
  echo To use this script please set the MINIBOXING_PATH and SCALA_PATH environment variables such that:
  echo " -" '$SCALA_PATH/scalac' "(currently $SCALA_PATH/scalac)"
  echo " -" '$MINIBOXING_PATH/components' "(currently $MINIBOXING_PATH/components)"
  echo are accessible
  exit 1
fi

SCALA_VERSION=2.10
MINIBOXING_VERSION=0.1
PLUGIN_JAR=$MINIBOXING_PATH/components/plugin/target/scala-$SCALA_VERSION/miniboxing-plugin_$SCALA_VERSION-$MINIBOXING_VERSION-SNAPSHOT.jar
RUNTIME_JAR=$MINIBOXING_PATH/components/runtime/target/scala-$SCALA_VERSION/miniboxing-runtime_$SCALA_VERSION-$MINIBOXING_VERSION-SNAPSHOT.jar

function checkjar {
  if [ ! -f "$1" ]
  then
    echo "The script is going to build the required jar file $1 by running \"sbt $2\" [5s until build]"
    sleep 5
    cd $MINIBOXING_PATH
    sbt $2
    cd -
    if [ ! -f "$1" ]
    then
      echo "The required jar file has not been built by sbt. Please run \"sbt $2\""
      exit 1
    else
      echo "The required jar file was built."
    fi
  fi
}

checkjar $PLUGIN_JAR miniboxing-plugin/package
checkjar $RUNTIME_JAR miniboxing-runtime/package

$SCALA_PATH/scala -J-Dminiboxing.log=true -bootclasspath $RUNTIME_JAR:$PLUGIN_JAR $@
