#!/bin/bash

SCALA_VERSION=2.11
MINIBOXING_VERSION=0.4-SNAPSHOT

if [ "$1" == "-2.10" ]
then
  SCALA_VERSION=2.10
  SCALA_PATH=$SCALA_PATH_210
  shift
fi

if [ "$MINIBOXING_PATH" == "" ] 
then 
  MINIBOXING_PATH="`dirname \"$0\"`"              # relative
  MINIBOXING_PATH="`( cd \"$MINIBOXING_PATH\" && pwd )`"  # absolutized and normalized
fi
if [ "$SCALA_PATH" == "" ] 
then
  SCALA_PATH="`dirname $(which scalac)`"
  SCALA_PATH="`( cd \"$SCALA_PATH\" && pwd )`"
fi

if [ "$MINIBOXING_PATH" == "" -o "$SCALA_PATH" == "" -o ! -f $SCALA_PATH/scalac -o ! -d $MINIBOXING_PATH/components ]
then
  echo To use this script please set the MINIBOXING_PATH and SCALA_PATH environment variables such that:
  echo " -" '$SCALA_PATH/scalac' "(currently $SCALA_PATH/scalac)"
  echo " -" '$MINIBOXING_PATH/components' "(currently $MINIBOXING_PATH/components)"
  echo are accessible
  exit 1
fi

PLUGIN_JAR=$MINIBOXING_PATH/components/plugin/target/scala-$SCALA_VERSION/miniboxing-plugin_$SCALA_VERSION-$MINIBOXING_VERSION.jar
RUNTIME_JAR=$MINIBOXING_PATH/components/runtime/target/scala-$SCALA_VERSION/miniboxing-runtime_$SCALA_VERSION-$MINIBOXING_VERSION.jar

me=`basename $0`
if [ "$me" == "mb-scalac" ]; then
  target=scalac
elif [ "$me" == "mb-scala" ]; then
  target=scala
else
  echo Unrecognized script name: $0
  exit 1
fi

function checkjar {
  if [ ! -f "$1" ]
  then
    echo "The script is going to build the required jar file $1 by running \"sbt $2\" [5s until build]"
    sleep 5
    cd $MINIBOXING_PATH
    sbt $2
    cd -
    if [ ! -f "$1" ]
    then
      echo "The required jar file has not been built by sbt. Please run \"sbt $2\""
      exit 1
    else
      echo "The required jar file was built."
    fi
  fi
}

checkjar $PLUGIN_JAR miniboxing-plugin/package
checkjar $RUNTIME_JAR miniboxing-runtime/package

$SCALA_PATH/$target -bootclasspath $RUNTIME_JAR:$PLUGIN_JAR -Xplugin:$PLUGIN_JAR $@
